#!/bin/bash

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4

CRONPROC=`systemctl status crond 2>/dev/null | sed -n "3p"`
CRONCHECK=`echo $CRONPROC | grep "Active: active (running)"`
CRONSTAT=`echo $?`
if [ "$CRONSTAT" -eq 0 ]
then
        PROCSTAT="0"
else
        CRONCHECK=`echo $CRONPROC | grep "Active: inactive (dead)"`
        CRONSTAT=`echo $?`
        if [ "$CRONSTAT" -eq 0 ]
        then
                PROCSTAT="1"
        else
                PROCSTAT="2"
                ERROR=`systemctl status crond 2>&1 > /dev/null`
        fi
fi

case "${PROCSTAT}" in
        0)  echo "$CRONPROC"; exit ${STATE_OK}
        ;;
        1)  echo "$CRONPROC"; exit ${STATE_CRITICAL}
        ;;
        2)  echo "$ERROR"; exit ${STATE_UNKNOWN}
        ;;
esac
